twig:
    file_name_pattern: '*.twig'
    form_themes: ['bootstrap_5_layout.html.twig']
    globals:
        ROLE:
            USER: 'ROLE_USER'
            ADMIN: 'ROLE_ADMIN'
        TOAST:
            FLASH_TYPE: 'TOAST'
            STATE_SUCCESS: 'SUCCESS'
            STATE_ERROR: 'ERROR'
            STATE_WARNING: 'WARNING'
    date:
        timezone: '%env(F1SONNTAG_DEFAULT_TIMEZONE)%'

when@test:
    twig:
        strict_variables: true
