twig:
    file_name_pattern: '*.twig'
    form_themes: ['bootstrap_5_layout.html.twig']
    globals:
        ROLE:
            USER: 'ROLE_USER'
            ADMIN: 'ROLE_ADMIN'
        TOAST_STATE:
            SUCCESS: 'SUCCESS'
            ERROR: 'ERROR'
            WARNING: 'WARNING'

when@test:
    twig:
        strict_variables: true
