twig:
    file_name_pattern: '*.twig'
    form_themes: ['bootstrap_5_layout.html.twig']
    globals:
        ROLE_USER: 'ROLE_USER'
        ROLE_ADMIN: 'ROLE_ADMIN'

when@test:
    twig:
        strict_variables: true
