version: '3'

services:
    mysql:
        image: 'mysql:${MYSQL_VERSION}'
        restart: 'unless-stopped'
        environment:
            MYSQL_DATABASE: f1sonntag
            MYSQL_PASSWORD: f1sonntag
            MYSQL_ROOT_PASSWORD: f1sonntag
            MYSQL_USER: f1sonntag
        volumes:
            - 'mysql-data:/var/lib/mysql:rw'
        ports:
            - '127.0.0.1:33060:3306'
    adminer:
        image: adminer
        restart: always
        ports:
            - 8080:8080

volumes:
    mysql-data:
