version: '3'

services:
    mysql:
        image: 'mysql:8.0'
        restart: 'unless-stopped'
        environment:
            MYSQL_DATABASE: f1sonntag
            MYSQL_PASSWORD: f1sonntag
            MYSQL_ROOT_PASSWORD: f1sonntag
            MYSQL_USER: f1sonntag
        volumes:
            - 'mysql-data:/var/lib/mysql:rw'
        ports:
            - '127.0.0.1:33060:3306'
volumes:
    mysql-data:
